micronaut:
  server:
    port: 8081
    max-request-size: '100MB'
    multipart:
      max-file-size: '100MB'
    cors:
      enabled: true
      single-header: true
      configurations:
        web:
          allowedMethods:
            - POST
            - GET
            - PUT
            - OPTIONS
          exposedHeaders:
            - Access-Control-Allow-Origin
            - Access-Control-Allow-Headers
            - Access-Control-Request-Method
            - Access-Control-Request-Headers
            - Origin
            - Cache-Control
            - Content-Type
            - Authorization
          allowedOrigins:
            - ^.*

---
application:
  max: 50
---
# this is for data module
datasources:
  default:
    url: ${JDBC_URL:`jdbc:h2:mem:default;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE`}
    username: ${JDBC_USER:sa}
    password: ${JDBC_PASSWORD:""}
    driverClassName: ${JDBC_DRIVER:org.h2.Driver}
---
jpa:
  default:
    packages-to-scan:
      - 'com.frankie.server.data.domain' # <1>
    properties:
      hibernate:
        hbm2ddl:
          auto: update
        show_sql: true